package NumberGame;

import java.util.Scanner;

public class Main {
	public static void main(String args[]) {
		Scanner scan = new Scanner(System.in);
		System.out.println(">>>>>>>>>>>>>>>>>>>>>>RULES OF THE GAME<<<<<<<<<<<<<<<<<<<<<<\n");
		System.out.println("1. You have to guess the number generated by system");
		System.out.println("2. You have 5 attemts to guess the number");
		System.out.println("3. You will lose 20 points for each incorrect guess");
		System.out.println("4. You won't lose any attempt count for invalid entry");
		System.out.println("5. System will provide hint for each attempt of incorrect guess\n");
		NumberGuessingGame(scan);
		boolean flag = false;
		do {
			System.out.println("Do You Want To Play Again : ");
			System.out.print("Enter Yes to play Again : ");
			scan.next();
			String choice = scan.nextLine();
			if (choice.equalsIgnoreCase(choice)) {
				NumberGuessingGame(scan);
			} else {
				flag = true;
			}
		} while (flag == false);
		System.out.println("End");
		scan.close();

	}

	public static void NumberGuessingGame(Scanner scan) {
		int randomNumber = (int) (Math.random() * 101 + 1);
		// System.out.println(randomNumber);

		int attempt = 1;
		int guessedNumber = 0;
		boolean flag = true;
		int k=1;
		while (k++ <=10 && flag == true) {
			System.out.println("******ATTEMPT " + (attempt++) + "********\n");
			System.out.print("Guess the Number : ");
			try {
				guessedNumber = scan.nextInt();
				if (guessedNumber <= 0 || guessedNumber > 100) {
					System.out.println("THE NUMBER IS BETWEEN 1 - 100 - ENTER A VALID NUMBER AGAIN\n");
					attempt--;
				} else {
					if (guessedNumber != randomNumber) {
						System.out.println("SORRY - YOUR GUESS IS INCORRECT - TRY AGAIN\n");
						System.out.println("HINT : " + hintGivingFunction(randomNumber, guessedNumber));

					} else {
						System.out.println("SUPER! - you guessed the correct Number\n");
						break;
					}
				}
			} catch (Exception e) {
				System.out.println("INVALID ENTRY OF NUMBER - ENTER A VALID INTEGER BETWEEN 1 - 100\n");
				scan.next();
				attempt--;
				guessedNumber = 0;
			}
		}
		System.out.println("your score is : " + scoreFunction(attempt) + " points\n");

	}

	public static String hintGivingFunction(int randomNumber, int guessedNumber) {
		if (randomNumber < guessedNumber) {
			return "NUMBER IS LESSER THAN " + guessedNumber + "\n";
		} else {
			return "NUMBER IS GREATER THAN " + guessedNumber + "\n";
		}
	}

	public static double scoreFunction(int attempts) {
		// total attempts = 5;
		return (double) ((5 - attempts + 2) * 20);
	}
}
